service: image-generator

provider:
  name: aws
  runtime: python3.6
  region: us-west-2

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: gen.png
          method: get
          contentHandling: CONVERT_TO_BINARY

plugins:
  - serverless-python-requirements
  - serverless-apigw-binary
  - serverless-apigwy-binary

custom:
  apigwBinary:
    types:
      - '*/*'
